### ISSUE TITLE
No map is showing when adding the plugin to a page

### ISSUE THREAD

**Issue by tbnobody** [zeichensatz/wok_gpxviewer#1]
I just see the height profile....

![image](https://user-images.githubusercontent.com/1753222/134749363-c09ed3d6-946a-41db-b9fb-88e5333a7804.png)

The javascript console shows the following errors:

```
leaflet.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at di (leaflet.js:5)
    at i._bringToBack (leaflet.js:5)
    at i.bringToBack (leaflet.js:5)
    at JB.Map.Polyline (osmutils.js:489)
    at JB.makeMap.showTracks (GPX2GM.js?1632522104:987)
    at GPX2GM.js?1632522104:667
```

First I tested it with Typo3 9.5 and then with 10.4... both times the same issue

**Comment by tbnobody** [comment]
I think I found a solution...

If I edit this line: https://github.com/zeichensatz/wok_gpxviewer/blob/ce5cb6c3dd12e6be4838f9726597a772c6e547f6/Resources/Private/Templates/Display/Index.html#L20

and change `height: 100%` to e.g. `height: 500px` it works.

**Comment by zeichensatz** [comment]
Are you using the bootstrap_package extension?

In this case you should check, if the class `.gpx-viewer` is defined. The class should be defined in wok_gpxviewer/Resources/Public/Scss/Theme/theme.scss with the values from wok_gpxviewer/Resources/Public/Scss/Theme/_variables.scss.
These values usually should only be changed in the constants of the extension.

In case you're not using the bootstrap_package extension you should try to define the class `.gpx-viewer` in your CSS code (see example below).

Changing the CSS is more flexible than changing the index.html. This way you can set up individual map heights on different pages.

The CSS code for my private website for example is:

`.gpx-viewer {
    border-style: solid;
    border-width: 1px;
    border-color: #477DBE;
    width: 100%;
    height: 600px;
}
`

Please let me know, if this reply was helpful to you.

**Comment by zeichensatz** [comment]
I was checking the issue more closely now.

When using the bootstrap_package I refer to the Scss parser, which is included in the bootstrap_package, for a more flexible setting of some parameters (see in the constants `GPXViewer: Basic`, `Scss Layout Settings (only working with bootstrap-package!)`.
If you're not using the bootstrap_package and you should set the constant plugin.tx_wokgpxviewer_gpxtracks.gpxviewer.scss to false. Then the CSS file `wok_gpxviewer/Resources/Public/CSS/custom.css` will be included.
The issue, which you experienced, probably is caused by this file. For test reasons I uncommented all the CSS in this file with `/* ... */`. Since I only use my extension with the bootstrap_package, I didn't really check the option for using this CSS file.

So if you're not using bootstrap_package, then you should do the following:

1.  Set the constant `plugin.tx_wokgpxviewer_gpxtracks.gpxviewer.scss = false`.
2. Copy the file `wok_gpxviewer/Resources/Public/CSS/custom.css` to the place, where you store your own CSS files.
3. Remove all uncommenting of CSS directives in this file.
4. Set the constant `plugin.tx_wokgpxviewer_gpxtracks.gpxviewer.cssFile = ToYourCssFile`.
5. If it's not working yet, please check, if your CSS file is really included on your page. May be the path/name isn't correct yet.

You may set the constants in the constant editor in `GPXVIEWER: BASIC`.

Please let me know, if this solves your issue.

**Comment by tbnobody** [comment]
I am using my own theme and inherited from the bootstrap_package theme. I have to check it again this evening but it seems I used the wrong order of the used template objects
This seems to work:
![grafik](https://user-images.githubusercontent.com/1753222/134870521-bdcdee20-b80a-4885-abb7-6561923851ee.png)

In my first version the theme was the last entry. Just give me this evening to revert the code changes I mentioned above and check it again.

**Comment by zeichensatz** [comment]
I also assume, the wrong order might have caused your issue. This reason didn't came into my mind.

Nevertheless I did change the custom.css file, so layout should also work if bootstrap_package isn't used (in case constant `plugin.tx_wokgpxviewer_gpxtracks.gpxviewer.scss = false`).

**Comment by tbnobody** [comment]
Just checked it. It was my fault. The wrong template order was the root cause. It's working now. Thank you!

**Comment by zeichensatz** [comment]
Thanks for checking!
I will add an according note to the "How to set up?" chapter.
